// apps/solidjs/src/routes/index.tsx
import { createFileRoute, Link } from '@tanstack/solid-router';
import { interpret } from '@bemedev/app';
import { useService } from '@bemedev/app-solidjs';
import { counterMachine } from '../machines/counter.machine';
import { trafficMachine } from '../machines/traffic.machine';
import { createSignal, onMount } from 'solid-js';

// Instantiate services
const counterService = interpret(counterMachine, {
  context: { count: 10, step: 1 },
});

const trafficService = interpret(trafficMachine, { context: { cycles: 0 } });

export const Route = createFileRoute('/')({
  component: () => {
    onMount(() => {
      counterService.start();
      trafficService.start();
    });

    // SolidJS accessors via @bemedev/app-solidjs
    const counterState = useService(counterService);
    const counterValue = useService(counterService, { selector: s => s.value });
    const counterCount = useService(counterService, { selector: s => s.context.count });
    
    const trafficState = useService(trafficService);
    const trafficTags = useService(trafficService, { selector: s => s.tags });

    return (
      <div class="space-y-8">
        {/* Hero Section */}
        <section class="p-8 rounded-2xl bg-gradient-to-r from-indigo-950/80 via-slate-900 to-purple-950/80 border border-indigo-500/20 shadow-2xl relative overflow-hidden">
          <div class="absolute -right-12 -top-12 w-64 h-64 bg-indigo-500/10 rounded-full blur-3xl pointer-events-none" />
          <div class="max-w-3xl relative z-10 space-y-4">
            <span class="px-3 py-1 text-xs font-semibold rounded-full bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
              TanStack Start + SolidJS Monorepo Integration
            </span>
            <h2 class="text-3xl md:text-4xl font-extrabold text-white tracking-tight">
              Visual Tester for <span class="bg-gradient-to-r from-indigo-400 via-pink-400 to-purple-400 bg-clip-text text-transparent">@bemedev/app</span> & <span class="bg-gradient-to-r from-cyan-400 to-blue-400 bg-clip-text text-transparent">@bemedev/app-solidjs</span>
            </h2>
            <p class="text-slate-300 leading-relaxed text-sm md:text-base">
              This application tests the reactivity middleware connecting <code class="text-pink-300 font-mono">@bemedev/app</code> state machines with SolidJS fine-grained signals using <code class="text-cyan-300 font-mono">useService</code>.
            </p>
          </div>
        </section>

        {/* Live Machine Cards Grid */}
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Machine 1: Counter */}
          <div class="p-6 rounded-2xl bg-slate-900/70 border border-slate-800 backdrop-blur shadow-xl space-y-5 flex flex-col justify-between">
            <div class="space-y-3">
              <div class="flex items-center justify-between">
                <span class="text-xs font-bold uppercase tracking-wider text-indigo-400">Machine 01</span>
                <span class="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                  {counterState().status}
                </span>
              </div>
              <h3 class="text-xl font-bold text-white">Counter State Machine</h3>
              <p class="text-xs text-slate-400">
                Tests basic transitions (<code class="text-indigo-300 font-mono">START</code>, <code class="text-indigo-300 font-mono">INC</code>, <code class="text-indigo-300 font-mono">DEC</code>, <code class="text-indigo-300 font-mono">STOP</code>) and reactive context accessors.
              </p>
            </div>

            <div class="p-4 rounded-xl bg-slate-950/80 border border-slate-800/80 space-y-3 font-mono text-xs">
              <div class="flex justify-between items-center">
                <span class="text-slate-500">State Value:</span>
                <span class="text-indigo-300 font-bold px-2 py-0.5 rounded bg-indigo-950 border border-indigo-800">
                  {JSON.stringify(counterValue())}
                </span>
              </div>
              <div class="flex justify-between items-center">
                <span class="text-slate-500">Count (via selector):</span>
                <span class="text-2xl font-black text-white">{counterCount()}</span>
              </div>
            </div>

            <div class="flex flex-wrap gap-2 pt-2">
              <button
                onClick={() => counterService.send('INC')}
                class="px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold shadow-lg shadow-indigo-600/30 transition-all active:scale-95 cursor-pointer"
              >
                Send INC
              </button>
              <button
                onClick={() => counterService.send('DEC')}
                class="px-4 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold border border-slate-700 transition-all active:scale-95 cursor-pointer"
              >
                Send DEC
              </button>
              <button
                onClick={() => counterService.send(counterValue() === 'idle' ? 'START' : 'STOP')}
                class="px-4 py-2 rounded-lg bg-purple-600 hover:bg-purple-500 text-white text-xs font-semibold shadow-lg shadow-purple-600/30 transition-all active:scale-95 cursor-pointer"
              >
                {counterValue() === 'idle' ? 'Start Machine' : 'Stop Machine'}
              </button>
              <Link
                to="/counter"
                class="ml-auto px-3 py-2 rounded-lg text-xs font-semibold text-indigo-400 hover:text-indigo-300 underline"
              >
                Full Test Route &rarr;
              </Link>
            </div>
          </div>

          {/* Machine 2: Traffic Light */}
          <div class="p-6 rounded-2xl bg-slate-900/70 border border-slate-800 backdrop-blur shadow-xl space-y-5 flex flex-col justify-between">
            <div class="space-y-3">
              <div class="flex items-center justify-between">
                <span class="text-xs font-bold uppercase tracking-wider text-purple-400">Machine 02</span>
                <span class="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-purple-500/20 text-purple-300 border border-purple-500/30">
                  Nested States
                </span>
              </div>
              <h3 class="text-xl font-bold text-white">Traffic & Speed Machine</h3>
              <p class="text-xs text-slate-400">
                Tests nested states (<code class="text-purple-300 font-mono">green.normal</code>, <code class="text-purple-300 font-mono">green.fast</code>) and state tags.
              </p>
            </div>

            <div class="p-4 rounded-xl bg-slate-950/80 border border-slate-800/80 space-y-3 font-mono text-xs">
              <div class="flex justify-between items-center">
                <span class="text-slate-500">State Value:</span>
                <span class="text-purple-300 font-bold px-2 py-0.5 rounded bg-purple-950 border border-purple-800">
                  {JSON.stringify(trafficState().value)}
                </span>
              </div>
              <div class="flex justify-between items-center">
                <span class="text-slate-500">Active Tags:</span>
                <div class="flex flex-wrap gap-1">
                  {(Array.isArray(trafficTags()) ? (trafficTags() as string[]) : trafficTags() ? [trafficTags() as string] : []).map((tag: string) => (
                    <span class="px-2 py-0.5 rounded-full text-[10px] font-semibold bg-purple-500/20 text-purple-300 border border-purple-500/30">
                      #{tag}
                    </span>
                  ))}
                </div>
              </div>
            </div>

            <div class="flex flex-wrap gap-2 pt-2">
              <button
                onClick={() => trafficService.send('NEXT')}
                class="px-4 py-2 rounded-lg bg-purple-600 hover:bg-purple-500 text-white text-xs font-semibold shadow-lg shadow-purple-600/30 transition-all active:scale-95 cursor-pointer"
              >
                Send NEXT
              </button>
              {typeof trafficState().value === 'object' && (
                <button
                  onClick={() =>
                    trafficService.send(
                      (trafficState().value as any).green === 'normal' ? 'ACCELERATE' : 'SLOW_DOWN'
                    )
                  }
                  class="px-4 py-2 rounded-lg bg-pink-600 hover:bg-pink-500 text-white text-xs font-semibold shadow-lg shadow-pink-600/30 transition-all active:scale-95 cursor-pointer"
                >
                  {(trafficState().value as any).green === 'normal' ? 'Accelerate' : 'Slow Down'}
                </button>
              )}
              <Link
                to="/traffic"
                class="ml-auto px-3 py-2 rounded-lg text-xs font-semibold text-purple-400 hover:text-purple-300 underline"
              >
                Full Test Route &rarr;
              </Link>
            </div>
          </div>
        </div>
      </div>
    );
  },
});

// apps/reactjs/src/routes/index.tsx
import { counterMachine } from '#/machines/counter';
import { cn } from '#/ui/cn';
import { Logs } from '#/ui/components/Logs';
import { MachineConfig } from '#/ui/components/MachineConfig';
import { Tags } from '#/ui/components/tags';
import { createFileRoute } from '@tanstack/react-router';
import {
  Activity,
  Code2,
  Cpu,
  Flame,
  Gauge,
  Layers,
  Minus,
  Plus,
  Sparkles,
  Square,
  Zap,
} from 'lucide-react';
import { Badge } from '../ui/components/badge';
import { Button } from '../ui/components/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '../ui/components/card';
import { useComponents } from './-index.components';

export const Route = createFileRoute('/')({
  component: () => {
    const service = Route.useRouteContext({
      select: s => s.counterService,
    });

    const {
      FullStateWrapper,
      Status,
      Count,
      Speed,
      StateValue,
      StateIdle,
      StateActive,
      StateFinal,
      StartStop,
      ActivateCounters,
      CanStop,
      Reset,
      sendEvent,
    } = useComponents(service);

    return (
      <div className=' text-slate-100 font-sans p-4 sm:p-8'>
        <div className='max-w-7xl mx-auto space-y-8'>
          {/* Header Hero Section */}
          <div className='relative overflow-hidden rounded-3xl border border-slate-800 bg-linear-to-b from-slate-900/90 to-slate-950/80 p-8 shadow-2xl backdrop-blur-2xl'>
            <div className='absolute top-0 right-0 -mr-16 -mt-16 h-64 w-64 rounded-full bg-emerald-500/10 blur-3xl' />
            <div className='absolute bottom-0 left-1/3 -mb-16 h-64 w-64 rounded-full bg-teal-500/10 blur-3xl' />
            <div className='relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-6'>
              <div className='space-y-3'>
                <div className='flex items-center gap-2'>
                  <Badge variant='active' className='text-xs'>
                    <Sparkles className='w-3.5 h-3.5' /> React 19 +
                    TanStack Start
                  </Badge>

                  <Badge variant='purple' className='text-xs'>
                    <Cpu className='w-3.5 h-3.5' /> @bemedev/app &
                    @bemedev/app-reactjs
                  </Badge>
                </div>

                <h1 className='text-3xl sm:text-4xl font-extrabold tracking-tight bg-linear-to-r from-white via-slate-200 to-emerald-400 bg-clip-text text-transparent'>
                  Visual State Machine Tester
                </h1>

                <p className='text-slate-400 max-w-2xl text-sm sm:text-base leading-relaxed'>
                  Test and inspect real-time state machine transitions with{' '}
                  <code className='text-emerald-400 font-mono'>
                    useService
                  </code>{' '}
                  from{' '}
                  <code className='text-teal-400 font-mono'>
                    @bemedev/app-reactjs
                  </code>
                  .
                </p>
              </div>

              {/* Service Status Card */}
              <div className='flex items-center gap-4 bg-slate-900/80 border border-slate-800 rounded-2xl p-4 shadow-inner'>
                <div className='space-y-1'>
                  <div className='text-xs text-slate-400 font-medium'>
                    Interpreter Status
                  </div>
                  <div className='flex items-center gap-2'>
                    <CanStop
                      render={canStop => (
                        <span
                          className={cn(
                            'h-3 w-3 rounded-full',
                            canStop
                              ? 'bg-rose-500'
                              : 'bg-emerald-400 animate-pulse shadow-lg shadow-emerald-400/50',
                          )}
                        />
                      )}
                    />
                    <Status />
                  </div>
                </div>

                <div className='h-8 w-px bg-slate-800' />
                <StartStop />
              </div>
            </div>
          </div>

          <MachineConfig
            config={counterMachine.config}
            title='Counter Machine Configuration'
          />

          {/* Dashboard Grid */}
          <div className='grid grid-cols-1 lg:grid-cols-3 gap-6'>
            {/* Column 1: Live State Cards */}
            <div className='space-y-6 lg:col-span-2'>
              {/* Live State Machine Status Card */}
              <Card>
                <CardHeader>
                  <CardTitle className='justify-between'>
                    <span className='flex items-center gap-2'>
                      <Activity className='w-5 h-5 text-emerald-400' />{' '}
                      State Inspector
                    </span>
                    <StateValue
                      render={v => {
                        const variant = v.includes('speed_high')
                          ? 'purple'
                          : v.includes('speed_low')
                            ? 'active'
                            : 'secondary';

                        return <Badge variant={variant}>{v}</Badge>;
                      }}
                    />
                  </CardTitle>
                  <CardDescription>
                    Current hierarchical state value and active tags
                  </CardDescription>
                </CardHeader>
                <CardContent className='space-y-6'>
                  {/* State Node Visual Display */}
                  <div className='grid grid-cols-1 sm:grid-cols-3 gap-3'>
                    <StateIdle />
                    <StateActive />
                    <StateFinal />
                  </div>

                  {/* Active Tags */}
                  <div className='space-y-2'>
                    <div className='text-xs text-slate-400 font-medium flex items-center gap-1.5'>
                      <Layers className='w-3.5 h-3.5 text-slate-400' />{' '}
                      Active Tags:
                    </div>

                    <Tags {...{ service }} />
                  </div>

                  {/* Context Counter Section */}
                  <div className='p-5 rounded-2xl bg-slate-950/80 border border-slate-800 flex items-center justify-between'>
                    <div>
                      <div className='text-xs font-medium text-slate-400 uppercase tracking-wider'>
                        Context Counter
                      </div>
                      <div className='text-3xl font-extrabold text-white mt-1'>
                        {<Count />}
                      </div>
                    </div>

                    <div className='flex items-center gap-2'>
                      <CanStop
                        render={disabled => (
                          <Button
                            variant='outline'
                            size='icon'
                            onClick={sendEvent('DEC')}
                            disabled={disabled}
                          >
                            <Minus className='w-4 h-4' />
                          </Button>
                        )}
                      />

                      <CanStop
                        render={disabled => (
                          <Button
                            variant='default'
                            size='icon'
                            onClick={sendEvent('INC')}
                            disabled={disabled}
                          >
                            <Plus className='w-4 h-4' />
                          </Button>
                        )}
                      />
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Interactive State Transition Controller */}
              <Card>
                <CardHeader>
                  <CardTitle className='flex items-center gap-2'>
                    <Zap className='w-5 h-5 text-amber-400' /> Dispatch
                    Events
                  </CardTitle>
                  <CardDescription>
                    Send events to trigger machine state transitions
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className='grid grid-cols-2 sm:grid-cols-4 gap-3'>
                    <ActivateCounters />
                    <CanStop
                      render={disabled => (
                        <Button
                          variant='secondary'
                          onClick={sendEvent('ACCELERATE')}
                          disabled={disabled}
                          className='gap-2'
                        >
                          <Flame className='w-4 h-4 text-amber-400' />{' '}
                          ACCELERATE
                        </Button>
                      )}
                    />
                    <CanStop
                      render={disabled => (
                        <Button
                          variant='secondary'
                          onClick={sendEvent('DECELERATE')}
                          disabled={disabled}
                          className='gap-2'
                        >
                          <Gauge className='w-4 h-4 text-sky-400' />{' '}
                          DECELERATE
                        </Button>
                      )}
                    />
                    <CanStop
                      render={disabled => (
                        <Button
                          variant='destructive'
                          onClick={sendEvent('STOP')}
                          disabled={disabled}
                          className='flex space-x-2 min-w-max'
                        >
                          <Square className='w-4 h-4' /> STOP COUNTERS
                        </Button>
                      )}
                    />
                  </div>

                  <Reset />
                </CardContent>
              </Card>

              {/* Hook Selector Verification Panel */}
              <Card>
                <CardHeader>
                  <CardTitle className='flex items-center gap-2'>
                    <Code2 className='w-5 h-5 text-sky-400' /> useService
                    Hook Selectors
                  </CardTitle>
                  <CardDescription>
                    Demonstrates selective reactive re-rendering with
                    options.selector
                  </CardDescription>
                </CardHeader>
                <CardContent className='grid grid-cols-1 md:grid-cols-2 gap-4'>
                  <div className='p-4 rounded-xl bg-slate-950/60 border border-slate-800 space-y-2'>
                    <div className='text-xs text-sky-400 font-mono'>
                      useService(service, &#123; selector: s =&gt;
                      s.context.count &#125;)
                    </div>

                    <div className='text-sm font-semibold text-slate-200'>
                      Extracted Count:{' '}
                      <span className='text-white font-bold'>
                        {<Count />}
                      </span>
                    </div>
                    <div className='text-xs text-sky-400 font-mono'>
                      useService(service, &#123; selector: s =&gt;
                      s.context.speed &#125;)
                    </div>
                    <div className='text-sm font-semibold text-slate-200'>
                      Extracted Speed:{' '}
                      <span className='text-white font-bold'>
                        {<Speed />}
                      </span>
                    </div>
                  </div>

                  <div className='p-4 rounded-xl bg-slate-950/60 border border-slate-800 space-y-2'>
                    <div className='text-xs text-teal-400 font-mono'>
                      useService(service, &#123; selector: s =&gt; s.value
                      &#125;)
                    </div>
                    <StateValue
                      render={v => (
                        <div className='text-sm font-semibold text-slate-200'>
                          State Value:{' '}
                          <span className='text-white font-bold'>{v}</span>
                        </div>
                      )}
                    />
                  </div>
                </CardContent>
              </Card>
            </div>
            <div className='space-y-6'>
              {/* Raw JSON Inspector */}
              <FullStateWrapper />
              <Logs {...{ service }} />
            </div>
          </div>
        </div>
      </div>
    );
  },
});
